/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-03-24 11:31:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.jdbc.Driver;
import java.sql.*;
import java.text.*;
import java.lang.String;

public final class author_005fajax_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");

	response.setContentType("text/xml; charset=UTF-8");
	response.setHeader("Cache-Control", "no-cache");
	String list = request.getParameter("list");
	String name = (String) session.getAttribute("userid");
	String name_s="",name_e="";
	
	if(list.equals("a")){
		name_s = name.substring(0,5)+"001";
		name_e = name.substring(0,5)+"100";
	}
	else if(list.equals("b")){
		name_s = name.substring(0,5)+"101";
		name_e = name.substring(0,5)+"FFF";		
	}
	
	
	String driverName = "com.mysql.jdbc.Driver";
	String userName = "root";
	String userPasswd = "102030";
	String dbName = "abc";
	String tableName = "users";
	//String tableName = request.getParameter("userName");
	String url = "jdbc:mysql://localhost/" + dbName + "?user=" + userName + "&password=" + userPasswd;
	Class.forName("com.mysql.jdbc.Driver").newInstance();
	Connection connection = DriverManager.getConnection(url);
	Statement statement = connection.createStatement();
	
	//String sql = "SELECT * FROM " + tableName;
	//String sql = "SELECT * FROM " + tableName +" where authority < '4' ORDER BY userID DESC ";
	
	String sql = "SELECT * FROM " + tableName +" where userName < '"
				+name_e+"' and userName >'"+name_s+"' ORDER BY userID DESC ";

	//String sql = "SELECT * FROM " + tableName + " ORDER BY id DESC LIMIT 21";
	ResultSet rs = statement.executeQuery(sql);	

	rs.last();
	int num = rs.getRow();
	String f = "%0" + 3 + "d";
	String numst = String.format(f, num);
	//System.out.println(numst);
	rs.first();
	out.println("<response>");
	out.println(list);
	out.println(numst);
	String data = rs.getString(2)+rs.getString(6);
	out.println(data);
	while (rs.next()) {
		data = rs.getString(2)+rs.getString(6);	 
 		out.println(data);
	}
	out.println("</response>");
	out.close();

	rs.close();
	statement.close();
	connection.close();

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
