/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-04-13 01:53:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.jdbc.Driver;
import java.sql.*;
import java.text.*;
import java.lang.String;

public final class user_005fajax_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


	String datetime=new SimpleDateFormat("yyyyMMdd").format( new java.util.Date());

	response.setContentType("text/xml; charset=UTF-8");  
    //response.setHeader("Cache-Control","no-cache");
    
	String userName = request.getParameter("userName");
	String userPWD = request.getParameter("userPWD");
	String author = request.getParameter("author");
	String mode = request.getParameter("mode");
	//int id = Integer.parseInt(uid);
	
	String driverName = "com.mysql.jdbc.Driver";
	String user = "root";
	String userPasswd = "102030";
	String dbName = "abc";
	String tableName = "users";
	//String tableName = request.getParameter("userName");
	String url = "jdbc:mysql://localhost/" + dbName + "?user=" + user + "&password=" + userPasswd;
	Class.forName("com.mysql.jdbc.Driver").newInstance();
	Connection connection = DriverManager.getConnection(url);
	Statement statement = connection.createStatement();
	//String sql = "SELECT * FROM " + tableName + " ORDER BY id DESC ";
	//String sql = "SELECT * FROM " + tableName + " ORDER BY id DESC LIMIT 21";
	//String sql = "SELECT * FROM " + tableName  + judge;	

	if(mode.equals("add")){
		String sql = "SELECT * FROM " + tableName + " where userName = '"+userName+"'";
		ResultSet rs = statement.executeQuery(sql);
		rs.last();
		int num = rs.getRow();
		if (num == 0) {
			sql = "insert into " + tableName + "(userName,userPWD,authority,creatime) " + "values('" + userName
					+ "','" + userPWD + "','" + author + "','" + datetime + "')";
			statement.executeUpdate(sql);
		}
	} else if (mode.equals("delete")) {
		String sql = "delete from " + tableName + " where userName = '" + userName + "'";
		statement.executeUpdate(sql);
	} else if (mode.equals("modify")) {
		String sql = "update " + tableName + " set userPWD='"+userPWD+"',authority='"+author+"' where userName = '" + userName + "'";
		statement.executeUpdate(sql);
	} else if (mode.equals("addev")) {
		String sql = "SELECT * FROM " + tableName + " where userName = '"+userName+"'";
		ResultSet rs = statement.executeQuery(sql);
		rs.last();
		int num = rs.getRow();
		if (num == 0) {
			sql = "insert into " + tableName + "(userName,userPWD,authority,creatime) " + "values('" + userName
					+ "','','8','" + datetime + "')";
			System.out.println(sql);
			statement.executeUpdate(sql);
		}
	}

	statement.close();
	connection.close();

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
