/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-04-26 03:08:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.jdbc.Driver;
import java.sql.*;
import java.net.Socket;
import java.text.SimpleDateFormat;

public final class authority_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>TW_WEB</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("#Container {\n");
      out.write("\t/* width: 1200px; */\n");
      out.write("\tmargin: 1 auto; /*设置整个容器在浏览器中水平居中*/\n");
      out.write("\t/* background: #CF3; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Header {\n");
      out.write("\theight: 40px;\n");
      out.write("\t/* background: #093; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo {\n");
      out.write("/* \tpadding-left: 50px;\n");
      out.write("\tpadding-top: 20px;\n");
      out.write("\tpadding-bottom: 50px; */\n");
      out.write("    padding-left: 1px;\n");
      out.write("\tpadding-top: 1px;\n");
      out.write("\tpadding-bottom: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content {\n");
      out.write("\theight: 540px;\n");
      out.write("\t/*此处对容器设置了高度，一般不建议对容器设置高度，一般使用overflow:auto;属性设置容器根据内容自适应高度，如果不指定高度或不设置自适应高度，容器将默认为1个字符高度，容器下方的布局元素（footer）设置margin-top:属性将无效*/\n");
      out.write("\tmargin-top: 20px; /*此处讲解margin的用法，设置content与上面header元素之间的距离*/\n");
      out.write("\t/* background: #0FF; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-Left {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 100px;\n");
      out.write("\tmargin: 20px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-Main {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 160px;\n");
      out.write("\tmargin: 20px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-View {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 500px;\n");
      out.write("\tmargin: 20px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* body {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0 0 12px 0;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\tline-height: 24px;\n");
      out.write("\tbackground: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("form, ul, li, p, h1, h2, h3, h4, h5, h6 {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input, select {\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\tline-height: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("img {\n");
      out.write("\tborder: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul li{\n");
      out.write("\tlist-style-type: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("\tcolor: #00007F;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a:hover {\n");
      out.write("\tcolor: #bd0a01;\n");
      out.write("\ttext-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".box {\n");
      out.write("\twidth: 150px;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu {\n");
      out.write("\toverflow: hidden;\n");
      out.write("\tborder-color: #C4D5DF;\n");
      out.write("\tborder-style: solid;\n");
      out.write("\tborder-width: 0 1px 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu li.level1 a {\n");
      out.write("\tdisplay: block;\n");
      out.write("\theight: 28px;\n");
      out.write("\tline-height: 28px;\n");
      out.write("\tbackground: #EBF3F8;\n");
      out.write("\tfont-weight: 700;\n");
      out.write("\tcolor: #5893B7;\n");
      out.write("\ttext-indent: 14px;\n");
      out.write("\tborder-top: 1px solid #C4D5DF;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu li.level1 a:hover {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu li.level1 a.current {\n");
      out.write("\tbackground: #B1D7EF;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".menu li ul {\n");
      out.write("\toverflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu li ul.level2 {\n");
      out.write("\tdisplay: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu li ul.level2 li a {\n");
      out.write("\tdisplay: block;\n");
      out.write("\theight: 28px;\n");
      out.write("\tline-height: 28px;\n");
      out.write("\tbackground: #ffffff;\n");
      out.write("\tfont-weight: 400;\n");
      out.write("\tcolor: #42556B;\n");
      out.write("\ttext-indent: 18px;\n");
      out.write("\tborder-top: 0px solid #ffffff;\n");
      out.write("\toverflow: hidden; \n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu li ul.level2 li a:hover {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write(".menu li ul.level2 li a.current {\n");
      out.write("\tbackground: #B1D7EF;\n");
      out.write("} */\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script src=\"http://www.codefans.net/ajaxjs/jquery-1.6.2.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/search.js\" charset= \"UTF-8\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/test.js\"></script>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t$(\".level1 > a\").click(function(){\n");
      out.write("\t\t$(this).addClass(\"current\")  //给当前元素添加\"current\"样式\n");
      out.write("\t\t.next().show()  //下一个元素显示\n");
      out.write("\t\t.parent().siblings().children(\"a\").removeClass(\"current\")   //父元素的兄弟元素的子元素<a>移除\"current\"样式\n");
      out.write("\t\t.next().hide();  //它们的下一个元素隐藏\n");
      out.write("\t\treturn false;\n");
      out.write("\t});\n");
      out.write("\t$(\".level2 > li a\").click(function(){\n");
      out.write("\t\t$(this).addClass(\"current\")  //给当前元素添加\"current\"样式\n");
      out.write("\t\t.next().show()  //下一个元素显示\n");
      out.write("\t\t.parent().siblings().children(\"a\").removeClass(\"current\")\n");
      out.write("\t\t/* .next().hide();  //它们的下一个元素隐藏 */\n");
      out.write("\t\treturn false;\n");
      out.write("\t});\t\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body background=\"image/DNA.jpg\">\n");
      out.write("\t");

		String name = (String) session.getAttribute("userid");
		String groupname = name.substring(0,5);
		
		String driverName = "com.mysql.jdbc.Driver";
		String userName = "root";
		String userPasswd = "102030";
		String dbName = "abc";
		String tableName = "users";
		//String tableName = request.getParameter("userName");
		String url = "jdbc:mysql://localhost/" + dbName + "?user=" + userName + "&password=" + userPasswd;
		Class.forName("com.mysql.jdbc.Driver").newInstance();
		Connection connection = DriverManager.getConnection(url);
		Statement statement = connection.createStatement();
		
		//String sql = "SELECT * FROM " + tableName;
		String sql = "SELECT * FROM " + tableName
				+" where userName = '"+name+"' and authority=3"; //
		//System.out.println(sql);
		//String sql = "SELECT * FROM " + tableName + " ORDER BY id DESC LIMIT 21";
		ResultSet rs = statement.executeQuery(sql);
		if(!rs.next()){
			response.sendRedirect("index.jsp");
			return;
		}
		
		//java.util.Date d = new java.util.Date();
		String datetime=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format( new java.util.Date());
		//String name = request.getParameter("userName"); // 接收表单参数
		boolean value7 = false;
	
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"Container\">\n");
      out.write("\t\t<div id=\"Header\">\n");
      out.write("\t\t\t<div id=\"logo\" style=\"font-size: 20px\">\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"运行界面\" style=\"margin:1px;width: 120px; height: 30px; background: #ADD8E6\" \n");
      out.write("\t\t\t\t\tonclick=\"href_new('user.jsp')\">  \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"数据查询\" style=\"margin:1px;width: 120px; height: 30px; background: #ADD8E6\" \n");
      out.write("\t\t\t\t\tonclick=\"href_new('search.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"数据分析\" style=\"margin:1px; width: 120px; height: 30px; background: #ADD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('line.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"视频\" style=\"margin:1px; width: 120px; height: 30px; background: #ADD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('video.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"管理员\" style=\"margin:1px; width: 120px; height: 30px; background: #EDD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('authority.jsp')\"> \n");
      out.write("\t\t\t\t用户名：");
      out.print(name);
      out.write(" 时间：");
      out.print(datetime);
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div id=\"Content-Main\">\n");
      out.write("\t\t\t<div style=\"line-height: 40px;\"\n");
      out.write("\t\t\t\tonClick=\"RequestUserList('a');showhide_obj('title6','icon6')\">\n");
      out.write("\t\t\t\t<font id='icon6'>+</font>用户列表\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"title6\"\n");
      out.write("\t\t\t\tstyle=\"background-color: #fffff3; line-height: 35px; display: none;\">\n");
      out.write("\t\t\t\t");

					//int usernum = 8;//Integer.parseInt(useridnumber);
					String menu6id, select6id, userlistid,userauthid;
					for (int i = 1; i < 10; i++) {
						//for (int i = 1; i <usernum ; i++) {
						menu6id = "menu6_" + i;
						select6id = "select6_" + i;
						userlistid = "userlistid" + i;
						userauthid = "userauthid" + i;
				
      out.write("\n");
      out.write("\t\t\t\t<span id=");
      out.print(menu6id);
      out.write(" onclick=\"show_userid('");
      out.print(userlistid);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(userauthid);
      out.write("');show_this('");
      out.print(select6id);
      out.write("')\">\n");
      out.write("\t\t\t\t\t<font id='");
      out.print(select6id);
      out.write("'></font> \n");
      out.write("\t\t\t\t\t<font id='");
      out.print(userlistid);
      out.write("'></font> \n");
      out.write("\t\t\t\t\t<input id='");
      out.print(userauthid);
      out.write("' type=\"hidden\">\n");
      out.write("\t\t\t\t</span><br />\n");
      out.write("\t\t\t\t");

					}				
				
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div style=\"line-height: 40px;\"\n");
      out.write("\t\t\t\tonClick=\"RequestUserList('b');showhide_obj('title7','icon7')\">\n");
      out.write("\t\t\t\t<font id='icon7'>+</font>设备列表\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"title7\"\n");
      out.write("\t\t\t\tstyle=\"background-color: #fffff3; line-height: 35px; display: none;\">\n");
      out.write("\t\t\t\t");

					//int usernum = 8;//Integer.parseInt(useridnumber);
					String menu7id, select7id, devlistid,devauthid;
					for (int i = 1; i < 10; i++) {
						//for (int i = 1; i <usernum ; i++) {
						menu7id = "menu7_" + i;
						select7id = "select7_" + i;
						devlistid = "devlistid" + i;
						devauthid = "devauthid" + i;
				
      out.write("\n");
      out.write("\t\t\t\t<span id=");
      out.print(menu7id);
      out.write(" onclick=\"show_devid('");
      out.print(devlistid);
      out.write("');show_this('");
      out.print(select7id);
      out.write("')\">\n");
      out.write("\t\t\t\t\t<font id='");
      out.print(select7id);
      out.write("'></font> \n");
      out.write("\t\t\t\t\t<font id='");
      out.print(devlistid);
      out.write("'></font> \n");
      out.write("\t\t\t\t\t<input id='");
      out.print(devauthid);
      out.write("' type=\"hidden\">\n");
      out.write("\t\t\t\t</span><br />\n");
      out.write("\t\t\t\t");

					}				
				
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"Content-Veiw\">\n");
      out.write("\t\t\t<table><tr>\n");
      out.write("\t\t\t<td width=\"90\"></td><td width=\"80\">用户名</td><td width=\"70\">密码</td><td width=\"80\">权限</td></tr></table>\n");
      out.write("\t\t\t<input type=\"text\" id='gpName' value=\"");
      out.print(groupname);
      out.write("\" style=\"width: 80px; height: 30px; margin:5px; text-align: right\" readonly=\"readonly\" />\n");
      out.write("\t\t\t<input type=\"text\" id='userName' style=\"width: 40px; height: 30px; margin:5px; text-align: right\" />\n");
      out.write("\t\t\t<input type=\"text\" id='userPWD' value=\"admin\" style=\"width: 80px; height: 30px; margin:5px; text-align: right\" /> \n");
      out.write("\t\t\t<input type=\"text\" id='author' style=\"width: 40px; height: 30px; margin:5px; text-align: right\" /><br /> \n");
      out.write("\t\t\t<input type=\"submit\" value=\"添加用户\" style=\"width: 80px; height: 30px; margin:5px\" \n");
      out.write("\t\t\t\t\tonclick=\"userfun('gpName','userName','userPWD','author','add')\"/> <br /> \n");
      out.write("\t\t\t<input type=\"submit\" value=\"删除用户\" style=\"width: 80px; height: 30px; margin:5px\" \n");
      out.write("\t\t\t\t\tonclick=\"userfun('gpName','userName','userPWD','author','delete')\" /><br /> \n");
      out.write("\t\t\t<input type=\"submit\" value=\"修改用户\" style=\"width: 80px; height: 30px; margin:5px\"\n");
      out.write("\t\t\t\t\tonclick=\"userfun('gpName','userName','userPWD','author','modify')\" /> <br /> \n");
      out.write("\t\t\t<br /> \n");
      out.write("\t\t\t<table><tr>\n");
      out.write("\t\t\t<td width=\"80\">设备名</td></tr></table>\n");
      out.write("\t\t\t<input type=\"text\" id='gpdName' value=\"");
      out.print(groupname);
      out.write("\" style=\"width: 80px; height: 30px; margin:5px; text-align: right\" readonly=\"readonly\" />\n");
      out.write("\t\t\t<input type=\"text\" id=\"devName\" style=\"width: 40px; height: 30px; margin:5px; text-align: right\" /> <br /> \n");
      out.write("\t\t\t<input type=\"submit\" value=\"添加设备\" style=\"width: 80px; height: 30px; margin:5px\" \n");
      out.write("\t\t\t\t\tonclick=\"userfun('gpName','devName','userPWD','userPWD','addev')\" /> <br /> \n");
      out.write("\t\t\t<input type=\"submit\" value=\"删除设备\" style=\"width: 80px; height: 30px; margin:5px\" \n");
      out.write("\t\t\t\t\tonclick=\"userfun('gpName','devName','userPWD','userPWD','delete')\" /> <br />\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
