/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-11-17 00:53:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.jdbc.Driver;
import java.sql.*;
import java.net.Socket;
import java.text.SimpleDateFormat;

public final class record_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>介绍</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("#Container {\n");
      out.write("\t/* width: 1200px; */\n");
      out.write("\tmargin: 1 auto; /*设置整个容器在浏览器中水平居中*/\n");
      out.write("\t/* background: #CF3; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Header {\n");
      out.write("\twidth:100%; \n");
      out.write("\theight: 30px;\n");
      out.write("\tline-height:30px; \n");
      out.write("\t/* background-color:#99ffff; */\n");
      out.write("\tFILTER: progid:DXImageTransform.Microsoft.Gradient(gradientType=2,startColorStr=#99ffaa,endColorStr=#99aaff); /*IE*/\n");
      out.write("\tbackground:-moz-linear-gradient(left,#99ffaa,#99aaff);/*火狐*/\n");
      out.write("\tbackground:-webkit-gradient(linear, 0% 0%, 100% 0%,from(#99ffaa), to(#99aaff));/*谷歌*/ \n");
      out.write("}\n");
      out.write("#Name {\t\n");
      out.write("\tpadding-left: 30px;\t\n");
      out.write("\twidth: 200px;\n");
      out.write("\tfloat: left; \n");
      out.write("}\n");
      out.write("\n");
      out.write("#Timer {\n");
      out.write("\tpadding-right: 30px;\n");
      out.write("\twidth: 300px;\n");
      out.write("\tfloat: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo {\n");
      out.write("    padding-left: 2px;\n");
      out.write("\tpadding-top: 5px;\n");
      out.write("\tpadding-bottom: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content {\n");
      out.write("\theight: 540px;\n");
      out.write("\tmargin-left:50px;\n");
      out.write("\tmargin-top:20px;\n");
      out.write("\t/*此处对容器设置了高度，一般不建议对容器设置高度，一般使用overflow:auto;属性设置容器根据内容自适应高度，如果不指定高度或不设置自适应高度，容器将默认为1个字符高度，容器下方的布局元素（footer）设置margin-top:属性将无效*/\n");
      out.write("\t/* margin-top: 20px; */ /*此处讲解margin的用法，设置content与上面header元素之间的距离*/\n");
      out.write("\t/* background: #0FF; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-Left {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 200px;\n");
      out.write("\tmargin: 20px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-Main {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 400px;\n");
      out.write("\tmargin: 20px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-View {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 300px;\n");
      out.write("\tmargin: 20px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("form, ul, li, p, h1, h2, h3, h4, h5, h6 {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("img {\n");
      out.write("\tborder: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul li{\n");
      out.write("\tlist-style-type: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("\tcolor: #00007F;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a:hover {\n");
      out.write("\tcolor: #bd0a01;\n");
      out.write("\ttext-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".box {\n");
      out.write("\twidth: 150px;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menul {\n");
      out.write("\toverflow: hidden;\n");
      out.write("\tborder-color: #C4D5DF;\n");
      out.write("\tborder-style: solid;\n");
      out.write("\tborder-width: 0 1px 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menul li.levela {\n");
      out.write("\tfloat:left;\n");
      out.write("\tmargin: 0px 2px 0px 2px;\n");
      out.write("\twidth: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menul li.levela a {\n");
      out.write("\tdisplay: block;\n");
      out.write("\theight: 28px;\n");
      out.write("\tline-height: 28px;\n");
      out.write("\tbackground: #EBF3F8;\n");
      out.write("\tfont-weight: 700;\n");
      out.write("\tcolor: #5893B7;\n");
      out.write("\t/* text-indent: 14px; */\n");
      out.write("\ttext-align:center;\n");
      out.write("\t/* border-top: 1px solid #C4D5DF; */\n");
      out.write("\tborder: 1px solid #C4D5DF;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menul li.levela a:hover {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menul li.levela a.current {\n");
      out.write("\tbackground: #B1D7EF;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".menul li ul {\n");
      out.write("\toverflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script src=\"js/jquery-1.6.2.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/search.js\" charset=\"UTF-8\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/functions.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<!-- <body background=\"image/DNA.jpg\"> -->\n");
      out.write("<body>\n");
      out.write("\t");

		String name = (String) session.getAttribute("userid");
		if (session.getAttribute("userid") == null) {
			response.sendRedirect("index.jsp");
			return;
		}
		//java.util.Date d = new java.util.Date();
		String datetime=new SimpleDateFormat("yyyy-MM-dd").format( new java.util.Date());
		//String name = request.getParameter("userName"); // 接收表单参数
		boolean value7 = false;
	
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"Container\">\n");
      out.write("\t\t<div id=\"Header\" >\n");
      out.write("\t\t\t<div id=\"Name\" style=\"color: #5893B7\"><h3>联舟技术</h3></div>\n");
      out.write("\t\t\t<div id=\"Timer\">\n");
      out.write("\t\t\t\t用户名：");
      out.print(name);
      out.write("\n");
      out.write("\t\t\t\t日期：");
      out.print(datetime);
      out.write("</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"logo\">\n");
      out.write("\t\t\t<ul class=\"menul\">\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('user.jsp')\" >隔离器</a></li>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('video.jsp')\" >视频直播</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('jiont.jsp')\"  >中产交互器</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('jiontreq.jsp')\" >中产终端</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('line.jsp')\" >数据分析</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('search.jsp')\" >数据查询</a></li>\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('upgrade.jsp')\" >远程升级</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('record.jsp')\" style=\"background: #EDD8E6\">介绍</a></li>\t\t\n");
      out.write("\t\t\t\t\t<li class=\"levela\" ><a onclick=\"href_new('authority.jsp')\" >管理登录</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"Content\">\n");
      out.write("\t\t\t<div id=\"Content-Left\">\n");
      out.write("\t\t\t\t<li style=\"line-height:200%\">电子自动化设计</li>\n");
      out.write("\t\t\t\t<li style=\"line-height:200%\">物联网数据路由器</li>\n");
      out.write("\t\t\t\t<li style=\"line-height:200%\">云服务器软件开发</li>\n");
      out.write("\t\t\t\t<li style=\"line-height:200%\">QQ:22960468</li>\n");
      out.write("\t\t\t\t<li style=\"line-height:200%\">QQ:283441008</li>\n");
      out.write("\t\t\t\t<li style=\"line-height:200%\">QQ:281436586</li>\n");
      out.write("\t\t\t\t<li style=\"line-height:200%\">用数据增加利润</li>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"Content-Main\">\n");
      out.write("\t\t\t\t<img src=\"image/lznet.jpg\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div id=\"Content-View\">\n");
      out.write("\t\t\t\t<img src=\"image/mycard.jpg\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- <div class=\"Clear\">如何你上面用到float,下面布局开始前最好清除一下。</div> -->\n");
      out.write("\t\t<div id=\"Footer\" style=\"font-size:12px;color:#5893B7\">\n");
      out.write("\t\t©2016 lianzhouiot 22960468@qq.com</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
