/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-03-24 12:56:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.jdbc.Driver;
import java.sql.*;
import java.net.Socket;
import java.text.SimpleDateFormat;
import console.pdf.CreatePDF;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>TW_WEB</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("table tr td { border-right:1px solid #000; border-bottom:1px solid #000;}\n");
      out.write("#Container {\n");
      out.write("\t/* width: 1200px; */\n");
      out.write("\tmargin: 1 auto; /*设置整个容器在浏览器中水平居中*/\n");
      out.write("\t/* background: #CF3; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Header {\n");
      out.write("\theight: 40px;\n");
      out.write("\t/* background: #093; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo {\n");
      out.write("/* \tpadding-left: 50px;\n");
      out.write("\tpadding-top: 20px;\n");
      out.write("\tpadding-bottom: 50px; */\n");
      out.write("    padding-left: 1px;\n");
      out.write("\tpadding-top: 1px;\n");
      out.write("\tpadding-bottom: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-View {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 1000px;\n");
      out.write("\tmargin: 10px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\" src=\"js/search.js\" charset= \"UTF-8\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/hsdate.js\" charset= \"UTF-8\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/test.js\" charset= \"UTF-8\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");

		String name = (String) session.getAttribute("userid");
		if (session.getAttribute("userid") == null) {
			response.sendRedirect("index.jsp");
			return;
		}
		//java.util.Date d = new java.util.Date();
		String datetime=new SimpleDateFormat("yyyy-MM-dd").format( new java.util.Date());
		//String name = request.getParameter("userName"); // 接收表单参数
		boolean value7 = false;
	
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"Container\">\n");
      out.write("\t\t<div id=\"Header\">\n");
      out.write("\t\t\t<div id=\"logo\" style=\"font-size: 20px\">\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"运行界面\" style=\"margin:1px;width: 120px; height: 30px; background: #ADD8E6\" \n");
      out.write("\t\t\t\t\tonclick=\"href_new('user.jsp')\">  \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"数据查询\" style=\"margin:1px;width: 120px; height: 30px; background: #EDD8E6\" \n");
      out.write("\t\t\t\t\tonclick=\"href_new('search.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"数据分析\" style=\"margin:1px; width: 120px; height: 30px; background: #ADD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('line.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"视频\" style=\"margin:1px; width: 120px; height: 30px; background: #ADD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('video.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"管理员\" style=\"margin:1px; width: 120px; height: 30px; background: #ADD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('authority.jsp')\"> \n");
      out.write("\t\t\t\t用户名：");
      out.print(name);
      out.write(" 时间：");
      out.print(datetime);
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"Content-View\">\n");
      out.write("            开始:<input type=\"text\" id='sdate' value=");
      out.print(datetime);
      out.write(" style=\"width:90px\" onfocus=\"HS_setDate(this)\">           \n");
      out.write("            结束:<input type=\"text\" id='edate' value=");
      out.print(datetime);
      out.write(" style=\"width:90px\" onfocus=\"HS_setDate(this)\">\n");
      out.write("\t\t\t批号:<input type=\"text\" id=\"number\" style=\"width:50px;text-align:right\"/>\n");
      out.write("\t\t\t设备:<input type=text id=\"devid\" style=\"width:50px;text-align:right\"/> \n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"查询\" style=\"width:60px\"\n");
      out.write("\t\t\t\tonclick=\"sendRequest('sdate','edate','number','devid','pageid')\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t<input class=\"call\" type=\"submit\" value=\"上页\" style=\"width: 60px\"\n");
      out.write("\t\t\t\tonclick=\"reduce();sendRequest('sdate','edate','number','devid','pageid')\"/> \n");
      out.write("\t\t\t<input type=text id=\"pageid\" value=\"1\" style=\"width:32px;text-align:right\"/>/\n");
      out.write("\t\t\t<input type=text id=\"pageall\" value=\"999\" style=\"width:32px;text-align:right\"/>\n");
      out.write("\t\t\t<input class=\"call\" type=\"submit\" value=\"下页\" style=\"width: 60px\" \n");
      out.write("\t\t\t\tonclick=\"add();sendRequest('sdate','edate','number','devid','pageid')\"/> \n");
      out.write("\t\t\t<input type=\"submit\" value=\"pdf\" style=\"width: 60px\" \n");
      out.write("\t\t\t\tonclick=\"sendpara('sdate','edate','number','devid')\"/> \n");
      out.write("\t\t\t<table>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td width=\"100\">日期</td>\n");
      out.write("\t\t\t\t\t<td width=\"100\">时间</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">设备号</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">批号</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">温度℃</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">湿度%RH</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">压差Pa</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">浓度ppm</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">风速m/s</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">时间min</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">状态</td>\n");
      out.write("\t\t\t\t\t<td width=\"80\">命令</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t\t");

					String dateid,timeid,devid,numid,tempid,humidityid,pressid,densityid;
					String windid,consumid,stateid,cmd;
					for (int i = 1; i<21; i++) {
						dateid = "dateid" + i;
						timeid = "timeid" + i;
						devid = "devid" + i;
						numid = "numid" + i;
						tempid = "tempid" + i;
						humidityid = "humidityid" + i;
						pressid = "pressid" + i;
						densityid = "densityid" + i;
						windid = "windid" + i;
						consumid = "consumid" + i;
						stateid = "stateid" + i;
						cmd = "cmd" + i;
				
      out.write("\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td width=\"100\" id=\"");
      out.print(dateid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"100\" id=\"");
      out.print(timeid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(devid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(numid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(tempid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(humidityid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(pressid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(densityid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(windid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(consumid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(stateid);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t<td width=\"80\" id=\"");
      out.print(cmd);
      out.write("\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
