/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-05-05 00:55:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.jdbc.Driver;
import java.sql.*;
import java.net.Socket;
import java.text.SimpleDateFormat;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>TW_WEB</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#Container {\n");
      out.write("\t/* width: 1200px; */\n");
      out.write("\tmargin: 1 auto; /*设置整个容器在浏览器中水平居中*/\n");
      out.write("\t/* background: #CF3; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Header {\n");
      out.write("\theight: 40px;\n");
      out.write("\t/* background: #093; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo {\n");
      out.write("/* \tpadding-left: 50px;\n");
      out.write("\tpadding-top: 20px;\n");
      out.write("\tpadding-bottom: 50px; */\n");
      out.write("    padding-left: 1px;\n");
      out.write("\tpadding-top: 1px;\n");
      out.write("\tpadding-bottom: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content {\n");
      out.write("\theight: 540px;\n");
      out.write("\t/*此处对容器设置了高度，一般不建议对容器设置高度，一般使用overflow:auto;属性设置容器根据内容自适应高度，如果不指定高度或不设置自适应高度，容器将默认为1个字符高度，容器下方的布局元素（footer）设置margin-top:属性将无效*/\n");
      out.write("\tmargin-top: 1px; /*此处讲解margin的用法，设置content与上面header元素之间的距离*/\n");
      out.write("\t/* background: #0FF; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-Left {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 100px;\n");
      out.write("\tmargin: 10px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-Main {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 150px;\n");
      out.write("\tmargin: 10px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#Content-View {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 300px;\n");
      out.write("\tmargin: 10px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("input#chat {\n");
      out.write("\twidth: 220px\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* #console-container {\n");
      out.write("\twidth: 400px;\n");
      out.write("} */\n");
      out.write("#console {\n");
      out.write("\tborder: 1px solid #CCCCCC;\n");
      out.write("\tborder-right-color: #999999;\n");
      out.write("\tborder-bottom-color: #999999;\n");
      out.write("\theight: 170px;\n");
      out.write("\toverflow-y: scroll;\n");
      out.write("\tpadding: 5px;\n");
      out.write("\twidth: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* #console p {\n");
      out.write("\tpadding: 0;\n");
      out.write("\tmargin: 0;\n");
      out.write("} */\n");
      out.write("\n");
      out.write("#Content-Set {\n");
      out.write("\theight: 500px;\n");
      out.write("\twidth: 300px;\n");
      out.write("\tmargin: 10px; /*设置元素跟其他元素的距离为20像素*/\n");
      out.write("\tfloat: left; /*设置浮动，实现多列效果，div+Css布局中很重要的*/\n");
      out.write("\t/* background: #cc0; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*注：Content-Left和Content-Main元素是Content元素的子元素，两个元素使用了float:left;设置成两列，这个两个元素的宽度和这个两个元素设置的padding、margin的和一定不能大于父层Content元素的宽度，否则设置列将失败*/\n");
      out.write("#Footer {\n");
      out.write("\theight: 40px;\n");
      out.write("\t/* background: #90C; */\n");
      out.write("\tmargin-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Clear {\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("        var Chat = {};\n");
      out.write("\n");
      out.write("        Chat.socket = null;\n");
      out.write("\n");
      out.write("        Chat.connect = (function(host) {\n");
      out.write("            if ('WebSocket' in window) {\n");
      out.write("                Chat.socket = new WebSocket(host);\n");
      out.write("            } else if ('MozWebSocket' in window) {\n");
      out.write("                Chat.socket = new MozWebSocket(host);\n");
      out.write("            } else {\n");
      out.write("                Console.log('Error: WebSocket is not supported by this browser.');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            Chat.socket.onopen = function () {\n");
      out.write("                Console.log('Info: WebSocket connection opened.');\n");
      out.write("                document.getElementById('chat').onkeydown = function(event) {\n");
      out.write("                    if (event.keyCode == 13) {\n");
      out.write("                        Chat.sendMessage();\n");
      out.write("                    }\n");
      out.write("                };\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            Chat.socket.onclose = function () {\n");
      out.write("                document.getElementById('chat').onkeydown = null;\n");
      out.write("                Console.log('Info: WebSocket closed.');\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            Chat.socket.onmessage = function (message) {\n");
      out.write("                Console.log(message.data);\n");
      out.write("                humidity(message.data);\n");
      out.write("            };\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        Chat.initialize = function() {\n");
      out.write("            if (window.location.protocol == 'http:') {\n");
      out.write("                Chat.connect('ws://' + window.location.host + '/webtest/websocket/chat');\n");
      out.write("            } else {\n");
      out.write("                Chat.connect('wss://' + window.location.host + '/webtest/websocket/chat');\n");
      out.write("            }\n");
      out.write("        };\n");
      out.write("        \n");
      out.write("   \n");
      out.write("        Chat.sendMessage = (function() {\n");
      out.write("        \tvar s = \"");
      out.print((String) session.getAttribute("userid"));
      out.write("\";\n");
      out.write("        \tvar e = document.getElementById('chat').value;\n");
      out.write("\t\t\tvar message = s.substring(0,5)+e.substring(6,9)+s.substring(6,9)+ ':tran:' + e;\n");
      out.write("\t\t\tif (message != '') {\n");
      out.write("\t\t\tChat.socket.send(message);\n");
      out.write("\t\t\tdocument.getElementById('chat').value = '';\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("        \n");
      out.write("    function Sendev(data){\n");
      out.write("    \tvar s = \"");
      out.print((String) session.getAttribute("userid"));
      out.write("\";\n");
      out.write("    \tvar e = document.getElementById(\"devid_select\").value\n");
      out.write("\n");
      out.write("\t\tvar message = s.substring(0,5)+e.substring(5,8)+s.substring(5,8)+ ':tran:'+e+':'+data;\n");
      out.write("\t\tChat.socket.send(message);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    function Sendev2(data,paraid){\n");
      out.write("    \tvar s = \"");
      out.print((String) session.getAttribute("userid"));
      out.write("\";\n");
      out.write("    \tvar e = document.getElementById(\"devid_select\").value\n");
      out.write("    \tvar f = document.getElementById(paraid).value\n");
      out.write("\n");
      out.write("\t\tvar message = s.substring(0,5)+e.substring(5,8)+s.substring(5,8)+ ':tran:'+e+':'+data+f;\t\n");
      out.write("\t\tChat.socket.send(message);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\tvar Console = {};\n");
      out.write("\n");
      out.write("\tConsole.log = (function(message) {\n");
      out.write("\t\tvar console = document.getElementById('console');\n");
      out.write("\t\tvar p = document.createElement('p');\n");
      out.write("\t\tp.style.wordWrap = 'break-word';\n");
      out.write("\t\tp.innerHTML = message;\n");
      out.write("\t\tconsole.appendChild(p);\n");
      out.write("\t\twhile (console.childNodes.length > 25) {\n");
      out.write("\t\t\tconsole.removeChild(console.firstChild);\n");
      out.write("\t\t}\n");
      out.write("\t\tconsole.scrollTop = console.scrollHeight;\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\tfunction humidity(message) {\n");
      out.write("\t\tdocument.getElementById('dataid1').value = message.substring(0, 2)+\".\"+message.substring(2, 3);\n");
      out.write("\t\tdocument.getElementById('dataid2').value = message.substring(3, 5)+\".\"+message.substring(5, 6);\n");
      out.write("\t\tdocument.getElementById('dataid3').value = message.substring(6, 9)+\".\"+message.substring(9, 10);\n");
      out.write("\t\tdocument.getElementById('dataid4').value = message.substring(10, 14);\n");
      out.write("\t\tdocument.getElementById('dataid5').value = message.substring(14, 15)+\".\"+message.substring(15, 17);\n");
      out.write("\t\tdocument.getElementById('dataid6').value = message.substring(17, 20);\n");
      out.write("\t\tdocument.getElementById('dataid7').value = message.substring(20, 21);\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tChat.initialize();\n");
      out.write("\n");
      out.write("\tdocument.addEventListener(\"DOMContentLoaded\", function() {\n");
      out.write("\t\t// Remove elements with \"noscript\" class - <noscript> is not allowed in XHTML\n");
      out.write("\t\tvar noscripts = document.getElementsByClassName(\"noscript\");\n");
      out.write("\t\tfor (var i = 0; i < noscripts.length; i++) {\n");
      out.write("\t\t\tnoscripts[i].parentNode.removeChild(noscripts[i]);\n");
      out.write("\t\t}\n");
      out.write("\t}, false);\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/search.js\" charset= \"UTF-8\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/test.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body background=\"image/DNA.jpg\">\n");
      out.write("\t");

		String name = (String) session.getAttribute("userid");
		if (session.getAttribute("userid") == null) {
			response.sendRedirect("index.jsp");
			return;
		}
		//java.util.Date d = new java.util.Date();
		String datetime=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format( new java.util.Date());
		//String name = request.getParameter("userName"); // 接收表单参数
		boolean value7 = false;
	
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"Container\">\n");
      out.write("\t\t<div id=\"Header\">\n");
      out.write("\t\t\t<div id=\"logo\" style=\"font-size: 20px\">\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"运行界面\" style=\"margin:1px;width: 120px; height: 30px; background: #EDD8E6\" \n");
      out.write("\t\t\t\t\tonclick=\"href_new('user.jsp')\">  \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"数据查询\" style=\"margin:1px;width: 120px; height: 30px; background: #ADD8E6\" \n");
      out.write("\t\t\t\t\tonclick=\"href_new('search.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"数据分析\" style=\"margin:1px; width: 120px; height: 30px; background: #ADD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('line.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"视频\" style=\"margin:1px; width: 120px; height: 30px; background: #ADD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('video.jsp')\"> \n");
      out.write("\t\t\t\t<input type=\"button\" value=\"管理员\" style=\"margin:1px; width: 120px; height: 30px; background: #ADD8E6\"\n");
      out.write("\t\t\t\t\tonclick=\"href_new('authority.jsp')\"> \n");
      out.write("\t\t\t\t用户名：");
      out.print(name);
      out.write(" 时间：");
      out.print(datetime);
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"Content\">\n");
      out.write("\t\t\t<div id=\"Content-Left\">\n");
      out.write("\t\t\t\t<div style=\"line-height: 40px;\"\n");
      out.write("\t\t\t\tonClick=\"RequestUserList('b');showhide_obj('title3','icon3')\">\n");
      out.write("\t\t\t\t<font id='icon3'>+</font>设备列表\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"title3\"\n");
      out.write("\t\t\t\tstyle=\"background-color: #fffff3; line-height: 35px; display: none;\">\n");
      out.write("\t\t\t\t");

					//int usernum = 8;//Integer.parseInt(useridnumber);
					String menu3id, select3id, devlistid,devauthid;
					for (int i = 1; i < 10; i++) {
						//for (int i = 1; i <usernum ; i++) {
						menu3id = "menu3_" + i;
						select3id = "select3_" + i;
						devlistid = "devlistid" + i;
						devauthid = "devauthid" + i;
				
      out.write("\n");
      out.write("\t\t\t\t<span id=");
      out.print(menu3id);
      out.write(" onclick=\"show_devid_all('");
      out.print(devlistid);
      out.write("');Sendev('AAZ');show_this('");
      out.print(select3id);
      out.write("')\">\n");
      out.write("\t\t\t\t\t<font id='");
      out.print(select3id);
      out.write("'></font> \n");
      out.write("\t\t\t\t\t<font id='");
      out.print(devlistid);
      out.write("'></font> \n");
      out.write("\t\t\t\t\t<input id='");
      out.print(devauthid);
      out.write("' type=\"hidden\">\n");
      out.write("\t\t\t\t</span><br />\n");
      out.write("\t\t\t\t");

					}				
				
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"Content-Main\" >\n");
      out.write("\t\t\t\t<div id=\"button1\" style=\"margin:5px\">\n");
      out.write("\t\t\t\t\t<input class=\"call\" type=\"submit\" value=\" 自动运行 \"\n");
      out.write("\t\t\t\t\t\tonclick=\"Sendev('AAA')\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 80px; height: 40px; background: #ADD8E6\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"button2\" style=\"margin:5px\">\n");
      out.write("\t\t\t\t\t<input class=\"call\" type=\"submit\" value=\"   除湿   \" \n");
      out.write("\t\t\t\t\t\tonclick=\"Sendev('AAB')\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 80px; height: 40px; background: #ADD8E6\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"button3\" style=\"margin:5px\">\n");
      out.write("\t\t\t\t\t<input class=\"call\" type=\"submit\" value=\"   加药   \"\n");
      out.write("\t\t\t\t\t\tonclick=\"Sendev('AAC')\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 80px; height: 40px; background: #ADD8E6\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"button4\" style=\"margin:5px\">\n");
      out.write("\t\t\t\t\t<input class=\"call\" type=\"submit\" value=\" 灭菌保持 \"\n");
      out.write("\t\t\t\t\t\tonclick=\"Sendev('AAD')\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 80px; height: 40px; background: #ADD8E6\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"button5\" style=\"margin:5px\">\n");
      out.write("\t\t\t\t\t<input class=\"call\" type=\"submit\" value=\"   通风   \"\n");
      out.write("\t\t\t\t\t\tonclick=\"Sendev('AAE')\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 80px; height: 40px; background: #ADD8E6\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"button6\" style=\"margin:5px\">\n");
      out.write("\t\t\t\t\t<input class=\"call\" type=\"submit\" value=\"   保压   \"\n");
      out.write("\t\t\t\t\t\tonclick=\"Sendev('AAF')\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 80px; height: 40px; background: #ADD8E6\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"Content-View\">\n");
      out.write("\t\t\t\t设备编号：<input type=\"text\" id=\"devid_select\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 100px; height: 30px; margin:5px\" readonly=\"readonly\"/> <br /> \n");
      out.write("\t\t\t\t当前温度: <input type=\"text\" id=\"dataid1\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" readonly=\"readonly\"/> ℃ <br />\n");
      out.write("\t\t\t\t当前湿度: <input type=\"text\" id=\"dataid2\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" readonly=\"readonly\"/> RH%<br /> \n");
      out.write("\t\t\t\t当前压差: <input type=\"text\" id=\"dataid3\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" readonly=\"readonly\"/> Pa<br />\n");
      out.write("\t\t\t\t当前浓度: <input type=\"text\" id=\"dataid4\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" readonly=\"readonly\"/> PPM<br /> \n");
      out.write("\t\t\t\t当前风速: <input type=\"text\" id=\"dataid5\" \n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" readonly=\"readonly\"/> m/s<br /> \n");
      out.write("\t\t\t\t持续时间: <input type=\"text\" id=\"dataid6\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" readonly=\"readonly\"/> min<br />\n");
      out.write("\t\t\t\t当前状态: <input type=\"text\" id=\"dataid7\" \n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" readonly=\"readonly\"/><br /> \n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div class=\"noscript\">\n");
      out.write("\t\t\t\t\t<h2 style=\"color: #ff0000\">Seems your browser doesn't support\n");
      out.write("\t\t\t\t\t\tJavascript! Websockets rely on Javascript being enabled. Please\n");
      out.write("\t\t\t\t\t\tenable Javascript and reload this page!</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"display:none\">\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"type and press enter to chat\"\n");
      out.write("\t\t\t\t\t\t\tid=\"chat\" />\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<div id=\"console\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"Content-Set\">\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t\t<!-- <input type=\"text\" id=\"savestate\" value=\"\" \n");
      out.write("\t\t\t\tstyle=\"width: 80px; height: 30px; color: blue; margin:5px\" /> <br />  -->\n");
      out.write("\t\t\t\t<input class=\"call\" type=\"submit\" value=\"读取参数\" onclick=\"Sendev('AAH')\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 100px; height: 30px; margin:5px\" />\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t<input class=\"call\" type=\"submit\" value=\"时间校正\" onclick=\"Sendev('AAG')\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 100px; height: 30px\" /><br /> \n");
      out.write("\n");
      out.write("\t 设定调节压差: <input type=\"text\" id='setpress' value=\"30\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" /> Pa.\n");
      out.write("\t\t\t\t<input class=\"call\" type=\"submit\" value=\"保存\" onclick=\"Sendev2('AB','setpress')\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" /><br /> \n");
      out.write("\t 设定灭菌时间: <input type=\"text\" id='setime1' value=\"50\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" /> min \n");
      out.write("\t\t\t\t <input class=\"call\" type=\"submit\" value=\"保存\" onclick=\"Sendev2('AC','setime1')\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" /><br /> \n");
      out.write("\t 设定通风时间: <input \ttype=\"text\" id='setime2' value=\"50\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" /> min \n");
      out.write("\t\t\t\t<input class=\"call\" type=\"submit\" value=\"保存\" onclick=\"Sendev2('AD','setime2')\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" /><br /> \n");
      out.write("\t 设定保压时间: <input type=\"text\" id='setime3' value=\"50\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" /> min \n");
      out.write("\t\t\t\t<input class=\"call\" type=\"submit\" value=\"保存\" onclick=\"Sendev2('AE','setime3')\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 50px; height: 30px; margin:5px\" /><br /> \n");
      out.write("<!-- \t\t\t\t<input class=\"call\" type=\"submit\" value=\"全部保存\" onclick=\"\"\n");
      out.write("\t\t\t\t\tstyle=\"width: 100px; height: 30px\" /> -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- <div class=\"Clear\">如何你上面用到float,下面布局开始前最好清除一下。</div> -->\n");
      out.write("\t\t<div id=\"Footer\">Footer</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
